name: bank
version: 1.0.1
description: >-
  Simulation of accounts with banking and controlling institutions.
author: Peter Loos <peter.loos@gmx.de>
homepage: http://peterloos.de
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
